### ISSUE TITLE
Small mistake in docs

### ISSUE THREAD

**Issue by luisfun** [EnkaNetwork/API-docs#13]
https://github.com/EnkaNetwork/API-docs/blob/b69f630bff18b2bfd06424bfe370a2aeae6f32f9/api.md?plain=1#L39

I found a small mistake in docs.

The correct code.
`| profilePicture.avatarId | Character ID of Profile Picture |`
"D" -> "d"

P.S.
I used this function for the first time. I'm sorry if I do anything wrong.

**Comment by Algoinde** [comment]
Thank you!
