### ISSUE TITLE
Plans on adding Serenitea Replica ID support?

### ISSUE THREAD

**Issue by ChrisMGeo** [EnkaNetwork/API-docs#30]
Similar to how you can validate player UID's will there be plans to be able to retrieve Serenitea replica information from Replica ID?

**Comment by GauravM512** [comment]
May I ask why you want to validate `Replica ID`?

**Comment by ChrisMGeo** [comment]
I think it'll make it easier to share replica ID's by validating them, and showing information like which realm layout or main building the replica is made on.
