### ISSUE TITLE
Datamine location

### ISSUE THREAD

**Issue by YousefSaadeh** [EnkaNetwork/API-docs#31]
![Screenshot_20221116_005347_com.github.android.jpg](https://user-images.githubusercontent.com/92186303/202033179-d697725f-f2df-46af-aa58-575769bf8b2d.jpg)

**Comment by Algoinde** [comment]
Repo was made private on the request of Mhy, you can join this [discord ](https://discord.gg/8Hpz2F7AnR) and request access in #datamine channel.

**Comment by YousefSaadeh** [comment]
> Repo was made private on the request of Mhy, you can join this [discord ](https://discord.gg/8Hpz2F7AnR) and request access in the #datamine channel.

Uh I see, thank you.. I will ^
