### ISSUE TITLE
How to get characters' art png file?

### ISSUE THREAD

**Issue by Mega-Z** [EnkaNetwork/API-docs#45]
I want to get characters' art png but dont know how to request. I have got the url for costume arts like "https://enka.network/ui/UI_Costume_AyakaCostumeFruhling.png" from store/characters.json. But what about the arts of default costumes or arts of characters that dont have a costume?

**Comment by Jelosus2** [comment]
You can use https://enka.network/ui/UI_Gacha_AvatarImg_Ayaka.png. Just replace the character name.

**Comment by Mega-Z** [comment]
> You can use https://enka.network/ui/UI_Gacha_AvatarImg_Ayaka.png. Just replace the character name.

that's helpful, thanks!
