### ISSUE TITLE
How to get character's talent level upgraded by constellations?

### ISSUE THREAD

**Issue by Mega-Z** [EnkaNetwork/API-docs#46]
or how to get character's information about which constellation can increase E or Q skill level by 3?

 I'm trying to get character's talent level from skillLevelMap, but the skill level seems like the base level without constellations.

**Comment by Jelosus2** [comment]
You may want to check `proudSkillExtraLevelMap`

**Comment by Mega-Z** [comment]
Thanks. But for example I got `proudSkillExtraLevelMap={'4239':3}` for KeQING-Cons3, while her skillLevelMap is like `{'10421': 10, '10422': 10, '10425': 10}`, how can I associate '4239'  with skill IDs?

**Comment by Algoinde** [comment]
Here's a chunk from my frontend code to illustrate
I'm using `characters.json` here in the repo that I generate every version.
![VSCodium_6134zgo0So](https://user-images.githubusercontent.com/10269970/221458340-1ba85e7b-b421-4420-aeee-c29a65273c86.png)

**Comment by Mega-Z** [comment]
thank you! that helps!
