### ISSUE TITLE
Questions and Suggestions

### ISSUE THREAD

**Issue by airdm** [EnkaNetwork/API-docs#5]
server = {
        "1": "cn_gf01",
        "2": "cn_gf01",
        "5": "cn_qd01",
        "6": "os_usa",
        "7": "os_euro",
        "8": "os_asia",
        "9": "os_cht",
    }
Hope it can support all server's UID inquiry. Aboves are the numbers that represent each servers.
May I ask do you have any plan about share the api and open sources for learning usage?

**Comment by Algoinde** [comment]
cnqd is the only one that is not yet supported; we're slightly reworking the architecture and the support should come soon.

**Comment by Algoinde** [comment]
I use some dark magic to get the data I get, so I'm not keen on disclosing the tools (yet). I do want the data to be as available as possible, but disclosing the toolkit might make it way more difficult to maintain the availability of data due to resultant changes.

**Comment by Algoinde** [comment]
Grasscutter and their Iridium fork would be a good starting point.

**Comment by Algoinde** [comment]
No problem! If [Discord ](https://discord.gg/PcSZr5sbn3) is available to you, you can hop on there to ask more questions (and get help using the API with your bot).
