### ISSUE TITLE
[Suggestion] Adding an entry for all characters to state what their codename is.

### ISSUE THREAD

**Issue by ShikiSuen** [EnkaNetwork/API-docs#55]
For example: Kirara's codename is Momoka, Jean's codename is Qin, Lyney's codename is Liney, etc.

**Comment by Algoinde** [comment]
It's in characters.json in this repo.
In addition, "codename" is not consistent across images. Use excels to get image URLs, not string concatenation.

**Comment by ShikiSuen** [comment]
@Algoinde Got it. Thanks. I found in [this file](https://github.com/EnkaNetwork/API-docs/blob/master/store/namecards.json) that Kirara's namecard is not named using her codename.
