### ISSUE TITLE
[Suggestion] Add character-related-namecard-bgs array to Characters.

### ISSUE THREAD

**Issue by ShikiSuen** [EnkaNetwork/API-docs#56]
This can allow devs to quickly search all possibly-related character namecard IDs from the characters.json file.

**Comment by Algoinde** [comment]
Namecards.json is what I use for myself on the frontend, and I don't need that data. It's here for reference and for a quick start. If you want more data or some other format of the data, you can just run a little script to create a data structure you want that will be suitable for your own application - namecards are in Materials, and you can link them with characters via Rewards excels.

**Comment by ShikiSuen** [comment]
@Algoinde Thanks. By the way you mentioned `excel`. Could you please tell me where to fetch these Excel files you have used for making these JSONs?

**Comment by Algoinde** [comment]
https://gitlab.com/Dimbreath/AnimeGameData
