### ISSUE TITLE
About Star Rail API docs

### ISSUE THREAD

**Issue by KishibeRohan1979** [EnkaNetwork/API-docs#58]
Hello, I recently saw that [[Enka.Network](https://enka.network/?hsr)](https://enka.network/?hsr) has updated related queries about Star Rail, so I would like to know if the relevant API docs about Star Rail will be released?

And Thank you for your contribution to Genshin API.

**Comment by kazuryyx** [comment]
Algoinde has told me that he will add HSR docs later, but that was around a month ago.
So yes, it is planned but I cannot really say more xD

**Comment by Algoinde** [comment]
HSR API has parity with March 7th API (released earlier).

Structure:
https://march7th.xiaohei.moe/en/resource/mihomo_api.html

Parser example:
https://github.com/Mar-7th/mihomo.py/blob/master/mihomo/api.py

**Comment by KishibeRohan1979** [comment]
OK I got it.
Thank you friends for your suggestions
