### ISSUE TITLE
Unable to get player's avatarId

### ISSUE THREAD

**Issue by Mega-Z** [EnkaNetwork/API-docs#61]
i've tried this api ：https://enka.network/api/uid/210441179.
but there's no "avatarId" in "profilePicture" field, only "id",
is there any way to get player's avatar image in Genshin?

**Comment by kazuryyx** [comment]
id = not migrated after 4.1
avatarId = migrated after 4.1 and may have costumeId field

**Comment by yuko1101** [comment]
you can use [ProfilePictureExcelConfigData.json](https://gitlab.com/Dimbreath/AnimeGameData/-/blob/master/ExcelBinOutput/ProfilePictureExcelConfigData.json?ref_type=heads) to get profile icons by the "id".

**Comment by Mega-Z** [comment]
thanks!
