### ISSUE TITLE
A question about image resources

### ISSUE THREAD

**Issue by Mega-Z** [EnkaNetwork/API-docs#65]
I tried to get the character card icons but failed, the urls are:

https://enka.network/ui/UI_AvatarIcon_Charlotte_Card.png
https://enka.network/ui/UI_AvatarIcon_Furina_Card.png
https://enka.network/ui/UI_AvatarIcon_Chevreuse_Card.png
https://enka.network/ui/UI_AvatarIcon_Navia_Card.png

i want to know if there's a method to fetch these images, thanks!

**Comment by kazuryyx** [comment]
Considering how Furina and Charlotte's Circle Icons are also missing, I assume Algoinde did not import them (yet). 
So you may have to wait until he does that
