### ISSUE TITLE
https://enka.network/ui/UI_ItemIcon_113052.png 404?

### ISSUE THREAD

**Issue by Value2299** [EnkaNetwork/API-docs#67]
It's the icon image of Wriothesley's ascend material, is there any other way I could get the image by this code "UI_ItemIcon_113052"?

**Comment by Algoinde** [comment]
Ambr.top CDN. I don't host what I don't use.

https://api.ambr.top/assets/UI/UI_ItemIcon_113052.png

**Comment by Value2299** [comment]
Thanks!
