### ISSUE TITLE
[Question] How to get namecard image url?

### ISSUE THREAD

**Issue by rushkii** [EnkaNetwork/API-docs#8]
It is an honor to all developers that this API goes public, I want to ask how to get namecard image url by the ID provided in the JSON? Thank you

**Comment by Jelosus2** [comment]
Sure, as you can see in the API there are parameters that show the id of your current namecard and the namecards you show in your profile. This is a file that contains information about the namecards: https://raw.githubusercontent.com/Dimbreath/GenshinData/master/ExcelBinOutput/MaterialExcelConfigData.json You can generate your own file with the info of the one i shared depending on what info you need of the namecards. You can use the ids of the namecards like a filter and then get the icons, which are like **UI_NameCardIcon_Ganyu**, **UI_NameCardPic_Ganyu_P** and **UI_NameCardPic_Ganyu_Alpha**, with that names you can make a request to `https://enka.shinshin.moe/ui/<Resource_Name>.png` to get the image. Example: `https://enka.shinshin.moe/ui/UI_NameCardPic_Ganyu_P.png`, hope it helps. If you have more questions or you don't understand something just write another message.

**Comment by rushkii** [comment]
> https://enka.shinshin.moe/ui/UI_NameCardPic_Ganyu_P.png

Oh, that helps. Thank you so much!
